FROM node:17-alpine3.14
ENV ADDRESSR_INDEX_TIMEOUT="30s"
ENV ADDRESSR_INDEX_BACKOFF="1000"
ENV ADDRESSR_INDEX_BACKOFF_INCREMENT="1000"
ENV ADDRESSR_INDEX_BACKOFF_MAX="10000"
ENV ELASTIC_PORT="9200"
ENV ELASTIC_HOST="host.docker.internal"
ENV ELASTIC_USERNAME=
ENV ELASTIC_PASSWORD=
ENV ELASTIC_PROTOCOL=
ENV NODE_ENV=production
RUN apk add --no-cache dumb-init && \
    npm install @mountainpass/addressr -g
ENTRYPOINT ["dumb-init", "--"]
CMD ["addressr-server"]
