---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.uname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
    {{- range $key, $value := .Values.elasticsearch.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    esMajorVersion: "{{ include "elasticsearch.esMajorVersion" . }}"
spec:
  serviceName: {{ template "elasticsearch.uname" . }}-headless
  selector:
    matchLabels:
      app: "{{ template "elasticsearch.uname" . }}"
  replicas: {{ .Values.elasticsearch.replicas }}
  podManagementPolicy: {{ .Values.elasticsearch.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.elasticsearch.updateStrategy }}
  {{- if .Values.elasticsearch.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "elasticsearch.uname" . }}
    {{- if .Values.elasticsearch.persistence.labels.enabled }}
      labels:
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "elasticsearch.uname" . }}"
        {{- range $key, $value := .Values.elasticsearch.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
{{ toYaml .Values.elasticsearch.volumeClaimTemplate | indent 6 }}
  {{- end }}
  template:
    metadata:
      name: "{{ template "elasticsearch.uname" . }}"
      labels:
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "elasticsearch.uname" . }}"
        {{- range $key, $value := .Values.elasticsearch.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.elasticsearch.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.elasticsearch.esConfig }}
        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      {{- if .Values.elasticsearch.schedulerName }}
      schedulerName: "{{ .Values.elasticsearch.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.elasticsearch.podSecurityContext | indent 8 }}
        {{- if .Values.elasticsearch.fsGroup }}
        fsGroup: {{ .Values.elasticsearch.fsGroup }} # Deprecated value, please use .Values.podSecurityContext.fsGroup
        {{- end }}
      {{- if .Values.elasticsearch.rbac.create }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- else if not (eq .Values.elasticsearch.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.elasticsearch.rbac.serviceAccountName | quote }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.elasticsearch.rbac.automountToken }}
      {{- with .Values.elasticsearch.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.elasticsearch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if or (eq .Values.elasticsearch.antiAffinity "hard") (eq .Values.elasticsearch.antiAffinity "soft") .Values.elasticsearch.nodeAffinity }}
      {{- if .Values.elasticsearch.priorityClassName }}
      priorityClassName: {{ .Values.elasticsearch.priorityClassName }}
      {{- end }}
      affinity:
      {{- end }}
      {{- if eq .Values.elasticsearch.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "{{ template "elasticsearch.uname" .}}"
            topologyKey: {{ .Values.elasticsearch.antiAffinityTopologyKey }}
      {{- else if eq .Values.elasticsearch.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.elasticsearch.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ template "elasticsearch.uname" . }}"
      {{- end }}
      {{- with .Values.elasticsearch.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.elasticsearch.terminationGracePeriod }}
      volumes:
        {{- range .Values.elasticsearch.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
            {{- end }}
        {{- end }}
        {{- if .Values.elasticsearch.esConfig }}
        - name: esconfig
          configMap:
            name: {{ template "elasticsearch.uname" . }}-config
        {{- end }}
{{- if .Values.elasticsearch.keystore }}
        - name: keystore
          emptyDir: {}
        {{- range .Values.elasticsearch.keystore }}
        - name: keystore-{{ .secretName }}
          secret: {{ toYaml . | nindent 12 }}
        {{- end }}
{{ end }}
      {{- if .Values.elasticsearch.extraVolumes }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.elasticsearch.extraVolumes) }}
{{ tpl .Values.elasticsearch.extraVolumes . | indent 8 }}
      {{- else }}
{{ toYaml .Values.elasticsearch.extraVolumes | indent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.elasticsearch.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.elasticsearch.imagePullSecrets | indent 8 }}
      {{- end }}
      enableServiceLinks: {{ .Values.elasticsearch.enableServiceLinks }}
      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.elasticsearch.hostAliases | nindent 8 }}
      {{- end }}
      {{- if or (.Values.elasticsearch.extraInitContainers) (.Values.elasticsearch.sysctlInitContainer.enabled) (.Values.elasticsearch.keystore)  }}
      initContainers:
      {{- if .Values.elasticsearch.sysctlInitContainer.enabled }}
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}"
        imagePullPolicy: "{{ .Values.elasticsearch.imagePullPolicy }}"
        command: ["sysctl", "-w", "vm.max_map_count={{ .Values.elasticsearch.sysctlVmMaxMapCount}}"]
        resources:
{{ toYaml .Values.elasticsearch.initResources | indent 10 }}
      {{- end }}
{{ if .Values.elasticsearch.keystore }}
      - name: keystore
        image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}"
        imagePullPolicy: "{{ .Values.elasticsearch.imagePullPolicy }}"
        command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          set -euo pipefail

          elasticsearch-keystore create

          for i in /tmp/keystoreSecrets/*/*; do
            key=$(basename $i)
            echo "Adding file $i to keystore key $key"
            elasticsearch-keystore add-file "$key" "$i"
          done

          # Add the bootstrap password since otherwise the Elasticsearch entrypoint tries to do this on startup
          if [ ! -z ${ELASTIC_PASSWORD+x} ]; then
            echo 'Adding env $ELASTIC_PASSWORD to keystore as key bootstrap.password'
            echo "$ELASTIC_PASSWORD" | elasticsearch-keystore add -x bootstrap.password
          fi

          cp -a /usr/share/elasticsearch/config/elasticsearch.keystore /tmp/keystore/
        env: {{ toYaml .Values.elasticsearch.extraEnvs | nindent 10 }}
        envFrom: {{ toYaml .Values.elasticsearch.envFrom | nindent 10 }}
        resources: {{ toYaml .Values.elasticsearch.initResources | nindent 10 }}
        volumeMounts:
          - name: keystore
            mountPath: /tmp/keystore
          {{- range .Values.elasticsearch.keystore }}
          - name: keystore-{{ .secretName }}
            mountPath: /tmp/keystoreSecrets/{{ .secretName }}
          {{- end }}
{{ end }}
      {{- if .Values.elasticsearch.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.elasticsearch.extraInitContainers) }}
{{ tpl .Values.elasticsearch.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.elasticsearch.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      - name: "{{ template "elasticsearch.name" . }}-es"
        securityContext:
{{ toYaml .Values.elasticsearch.securityContext | indent 10 }}
        image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}"
        imagePullPolicy: "{{ .Values.elasticsearch.imagePullPolicy }}"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e

                # Exit if ELASTIC_PASSWORD in unset
                if [ -z "${ELASTIC_PASSWORD}" ]; then
                  echo "ELASTIC_PASSWORD variable is missing, exiting"
                  exit 1
                fi

                # If the node is starting up wait for the cluster to be ready (request params: "{{ .Values.elasticsearch.clusterHealthCheckParams }}" )
                # Once it has started only check that the node itself is responding
                START_FILE=/tmp/.es_start_file

                # Disable nss cache to avoid filling dentry cache when calling curl
                # This is required with Elasticsearch Docker using nss < 3.52
                export NSS_SDB_USE_CACHE=no

                http () {
                  local path="${1}"
                  local args="${2}"
                  set -- -XGET -s

                  if [ "$args" != "" ]; then
                    set -- "$@" $args
                  fi

                  set -- "$@" -u "elastic:${ELASTIC_PASSWORD}"

                  curl --output /dev/null -k "$@" "{{ .Values.elasticsearch.protocol }}://127.0.0.1:{{ .Values.elasticsearch.httpPort }}${path}"
                }

                if [ -f "${START_FILE}" ]; then
                  echo 'Elasticsearch is already running, lets check the node is healthy'
                  HTTP_CODE=$(http "/" "-w %{http_code}")
                  RC=$?
                  if [[ ${RC} -ne 0 ]]; then
                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.elasticsearch.protocol }}://127.0.0.1:{{ .Values.elasticsearch.httpPort }}/ failed with RC ${RC}"
                    exit ${RC}
                  fi
                  # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
                  if [[ ${HTTP_CODE} == "200" ]]; then
                    exit 0
                  elif [[ ${HTTP_CODE} == "503" && "{{ include "elasticsearch.esMajorVersion" . }}" == "6" ]]; then
                    exit 0
                  else
                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.elasticsearch.protocol }}://127.0.0.1:{{ .Values.elasticsearch.httpPort }}/ failed with HTTP code ${HTTP_CODE}"
                    exit 1
                  fi

                else
                  echo 'Waiting for elasticsearch cluster to become ready (request params: "{{ .Values.elasticsearch.clusterHealthCheckParams }}" )'
                  if http "/_cluster/health?{{ .Values.elasticsearch.clusterHealthCheckParams }}" "--fail" ; then
                    touch ${START_FILE}
                    exit 0
                  else
                    echo 'Cluster is not yet ready (request params: "{{ .Values.elasticsearch.clusterHealthCheckParams }}" )'
                    exit 1
                  fi
                fi
{{ toYaml .Values.elasticsearch.readinessProbe | indent 10 }}
        ports:
        - name: http
          containerPort: {{ .Values.elasticsearch.httpPort }}
        - name: transport
          containerPort: {{ .Values.elasticsearch.transportPort }}
        resources:
{{ toYaml .Values.elasticsearch.resources | indent 10 }}
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if has "master" .Values.elasticsearch.roles }}
          - name: cluster.initial_master_nodes
            value: "{{ template "elasticsearch.endpoints" . }}"
          {{- end }}
          - name: node.roles
            value: "{{ template "elasticsearch.roles" . }}"
          {{- if lt (int (include "elasticsearch.esMajorVersion" .)) 7 }}
          - name: discovery.zen.ping.unicast.hosts
            value: "{{ template "elasticsearch.masterService" . }}-headless"
          {{- else }}
          - name: discovery.seed_hosts
            value: "{{ template "elasticsearch.masterService" . }}-headless"
          {{- end }}
          - name: cluster.name
            value: "{{ .Values.elasticsearch.clusterName }}"
          - name: network.host
            value: "{{ .Values.elasticsearch.networkHost }}"
          {{- if .Values.elasticsearch.secret.enabled }}
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "elasticsearch.uname" . }}-credentials
                key: password
          {{- end }}
          {{- if .Values.elasticsearch.esJavaOpts  }}
          - name: ES_JAVA_OPTS
            value: "{{ .Values.elasticsearch.esJavaOpts }}"
          {{- end }}
{{- if .Values.elasticsearch.extraEnvs }}
{{ toYaml .Values.elasticsearch.extraEnvs | indent 10 }}
{{- end }}
{{- if .Values.elasticsearch.envFrom }}
        envFrom:
{{ toYaml .Values.elasticsearch.envFrom | indent 10 }}
{{- end }}
        volumeMounts:
          {{- if .Values.elasticsearch.persistence.enabled }}
          - name: "{{ template "elasticsearch.uname" . }}"
            mountPath: /usr/share/elasticsearch/data
          {{- end }}
{{ if .Values.elasticsearch.keystore }}
          - name: keystore
            mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
            subPath: elasticsearch.keystore
{{ end }}
          {{- range .Values.elasticsearch.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- range $path, $config := .Values.elasticsearch.esConfig }}
          - name: esconfig
            mountPath: /usr/share/elasticsearch/config/{{ $path }}
            subPath: {{ $path }}
          {{- end -}}
        {{- if .Values.elasticsearch.extraVolumeMounts }}
        # Currently some extra blocks accept strings
        # to continue with backwards compatibility this is being kept
        # whilst also allowing for yaml to be specified too.
        {{- if eq "string" (printf "%T" .Values.elasticsearch.extraVolumeMounts) }}
{{ tpl .Values.elasticsearch.extraVolumeMounts . | indent 10 }}
        {{- else }}
{{ toYaml .Values.elasticsearch.extraVolumeMounts | indent 10 }}
        {{- end }}
        {{- end }}
{{- if .Values.elasticsearch.lifecycle }}
        lifecycle:
{{ toYaml .Values.elasticsearch.lifecycle | indent 10 }}
{{- end }}
      {{- if .Values.elasticsearch.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.elasticsearch.extraContainers) }}
{{ tpl .Values.elasticsearch.extraContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.elasticsearch.extraContainers | indent 6 }}
      {{- end }}
      {{- end }}
