apiVersion: v1
kind: Service
metadata:
  annotations:
    # important for appending href uri to addressr http server
    konghq.com/path: /addresses
  name: {{ include "addressr.fullname" . }}
  labels:
    {{- include "addressr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "addressr.selectorLabels" . | nindent 4 }}
